# Generated by Django 4.2.5 on 2023-11-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0003_loginform_registrationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdetails',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
