# Generated by Django 4.2.5 on 2023-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0005_cart_qty_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
